services:
  app:
    build: .
    container_name: ecommerce_app
    ports:
      - "808:808"  # 호스트:컨테이너
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/ecommerce?characterEncoding=UTF-8&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - ecommerce_net

  db:
    image: mysql:8.0
    container_name: ecommerce_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    networks:
      - ecommerce_net
    volumes:
      - ./mysql_data:/var/lib/mysql

  nginx:
    image: nginx:latest
    container_name: ecommerce_nginx
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - ecommerce_net

volumes:
  db_data:

networks:
  ecommerce_net:
    driver: bridge
