pipeline {
    agent any

    stages {


        stage('Install Dependencies') {
            steps {
                script {
                    sh 'corepack enable'
                    sh 'pnpm install'
                }
            }
        }

        stage('Build') {
            steps {
                sh 'pnpm next build'
            }
        }

        stage('Deploy') {
            steps {
                sh 'pm2 restart ecosystem.config.js'
            }
        }
    }
}
